import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Hammersmith_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-geist-montserrat",
});

const hammersmith = Hammersmith_One({
  variable: "--font-hammersmith",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Viaja con Ludmi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${geistMono.variable} ${hammersmith.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
